applications/dep/urls.py
from django.contrib import admin
from django.urls import path
urlpatterns = [


]

applications/emp/urls.py
from django.contrib import admin
from django.urls import path
from .views import listAllEmployeesListView,listByAreaListView,listBySearchListView,skillsEmployeeListView,employeeDetailView,employeeCreateView,successView,employeeUpdateView,employeeDeleteView
app_name ='emp_app'
urlpatterns = [
    #path
    # (
         #nombreParaLaURL#,
         #vista.as_view(),
         #nombre='nombreDeLaVista'    
    #)
    path(
        'allEmployees/',
        listAllEmployeesListView.as_view(),
        name='allEmployees'),
    
    path('byArea/<var>/',
         listByAreaListView.as_view(),
         name='byArea'),
    
    path("search/"
         ,listBySearchListView.as_view(),
         name='search'),
    
    path('skills/',
         skillsEmployeeListView.as_view(),
         name='skills'),
    
    path('detail/<pk>',
         employeeDetailView.as_view(),
         name='detail'),
    
    path('register/',
         employeeCreateView.as_view(),
         name='register'),
    
    path('success/',
         successView.as_view(),
         name='success'),
    path(
     'update/<pk>',
     employeeUpdateView.as_view(),
     name='update'
    ),
    path(
     'delete/<pk>',
     employeeDeleteView.as_view(),
     name='detele'
    ),
]

proyectoEmpleados/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.dep.urls')),
    path('',include('applications.emp.urls')),
]

applications/dep/models.py
from django.db import models

# Create your models here.
class dep(models.Model):
    name = models.CharField('Nombre', max_length=60,blank=True)
    shortName = models.CharField('Nombre Corto', max_length=20,unique=True)
    anulate = models.BooleanField('Anulado',default=False)
    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'departament'
        verbose_name_plural = 'departaments'
        ordering=['name']
        unique_together=('name','shortName')
        
    def __str__(self):
        return str(self.id)+ ' ' +self.name+ ' ' +self.shortName
    

applications/emp/models.py
from django.db import models
from ..dep.models import dep
# Create your models here.
class skills(models.Model):
    skill = models.CharField('Habilidad', max_length=50)
    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'skill'
        verbose_name_plural = 'skills'
        ordering=['skill']
    def __str__(self):
        return self.skill # TODO
class employee(models.Model):
    #aqui se crea los campos del modelo y dentro del los campos se especidica los datos
    firstName=models.CharField("Nombre(s)", max_length=60)
    lastName = models.CharField('Apellido(s)', max_length=60)
    fullName = models.CharField("Nombre Completo",max_length=120,blank=True)
    email = models.EmailField('Email', max_length=50,unique=True)
    # contador
    # administrador
    # economista
    # ingeniero 
    # otro
    JOB_CHOICES=(
        ('0','Ingeniero'),
        ('1','Practicante'),
        ('2','Administrador'),
        ('3','Contador'),
        ('4','RH'),
        ('5','Cliente')
    )
    job = models.CharField('Puesto', max_length=1,choices=JOB_CHOICES)
    dep = models.ForeignKey(dep, on_delete=models.CASCADE)
    skill = models.ManyToManyField(skills)
    #FOTO = models.ImageField('Foto', upload_to=None, height_field=None, width_field=None, max_length=None)
    class Meta:
        db_table = ''
        managed = True
        verbose_name = 'employee'
        verbose_name_plural = 'employees'
        ordering=['id','firstName','lastName','email','dep']
        unique_together=('email',)
        
    def __str__(self):
        return str(self.firstName)+ ' ' +self.lastName+ ' ' +self.email+' '+self.job 

applications/dep/forms.py
from django import forms

class newDepartamentoForm(forms.Form):
    firstName = forms.CharField(max_length=50)
    lastName=  forms.CharField(max_length=50)
    depName=  forms.CharField(max_length=50)
    shortName= forms.CharField(max_length=20)
    

applications/dep/views.py
from django.shortcuts import render
from django.views.generic.edit import FormView
from .models import dep
# Create your views here.
class newDepView(FormView):
    pass;

templates/dep/listDep.html
{%extends 'base.html'%}

{%block title%}
Lista Dep
{%endblock title%}
{%block content%}

<!-- <ul>
{% for d in employees  %}
<li>{{d.firstName}}</li>
{% endfor %}
</ul> -->
{%include 'includes/header.html'%}
<div class="grid-container">
  <div class="grix-x">
    <h2 class="cell">Lista De Departamentos {{Area}}</h2>
    <div class="cell grid-x grid-margin-x">
      <form method="get" class=" grid-x grid-margin-x">{%csrf_token%}
        <div class="cell large-10">
          <input type="text" name="search_dep" id="search_dep" placeholder="Buscar Departamento Por Nombre">
        </div>
        <div class="cell large-2">
          <button class="button success" id="search" name="search" type="submit">Buscar</button>
        </div>
      </form>
      <div class="cell">
        <table>
          <tr>
            <td>Nombre</td>
            <td>Disponibilidad</td>
            <td>Accion</td>
          </tr>
          {% for d in dep %}
          <tr>
            <td>{{d.name}}</td>
           
           {% if not d.anulate %}
            <td>Disponible</td>
            {% else %} <td>No Disponible</td>
            {% endif %}
            <td>
              <a class="button warning" href="{%url 'emp_app:byArea' d.id%}" id="emp_view"
                name="emp_view">Ver</a></td>
          </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
  {% if is_paginated %}
  <nav>
    <ul class="pagination text-center">
      {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number}}" aria-label="Page">Antes</a></li>

      {% endif %}
      {% for i in paginator.page_range %}


      {% if i == page_obj.number %}

      <li class="current"><span class="show-for-sr"></span>{{i}}</li>
      {% else %}
      <li><a href="?page={{i}}" aria-label="Page">{{i}}</a></li>
      {% endif %}


      {% endfor %}
      {% if page_obj.has_next %}
      <li>
        <a href="?page={{ page_obj.next_page_number }}">Siguiente
      </li>
      {% else %}

      {% endif %}
    </ul>
  </nav>
  {% endif %}

  {%endblock content%}

templates/dep/registerDep.html
{% extends 'base.html' %}
{% block title %}
Registro De Departamento
{% endblock title %}

{% block content %}
{% include 'includes/header.html' %}

<h2>Registar Un Departamento</h2>
<div class="grid-container">
    <form method="post" class="grid-x grid-margin-x">{% csrf_token %}
        <h3 class="cell">Nombre Del Empleado</h3>
        
        <div class="cell large-4">
            <label for="id_firstName">Nombre: </label>{{form.firstName}}
        </div>
        <div class="cell large-4">
            <label for="id_lastName">Apellido(s): </label>{{form.lastName}}

        </div>
        <div class="cell large-4">
            <label for="id_email">Email: </label>{{form.email}}

        </div>
        <h3 class="cell">Nombre Del Departamento</h3>
        <div class="cell large-4">
            <label for="id_dep">Nombre Del Departamento: </label>{{form.dep}}

        </div>
        <div class="cell large-4">
            <label for="id_shortName">Nombre Corto: </label>{{form.shortName}}

        </div>
        <div class="cell large-12">
            <input class="button success" style="color: azure;" type="submit" value="Registar">
        </div>
    </form>
</div>

{% endblock content %}
    
    |