applications/emp/urls.py
from django.contrib import admin
from django.urls import path
from .views import listAllEmployeesListView,listByAreaListView,listBySearchListView,skillsEmployeeListView,employeeDetailView,employeeCreateView,successView,employeeUpdateView,employeeDeleteView
app_name ='emp_app'
urlpatterns = [
    #path
    # (
         #nombreParaLaURL#,
         #vista.as_view(),
         #nombre='nombreDeLaVista'    
    #)
    path(
        'allEmployees/',
        listAllEmployeesListView.as_view(),
        name='allEmployees'),
    
    path('byArea/<var>/',
         listByAreaListView.as_view(),
         name='byArea'),
    
    path("search/"
         ,listBySearchListView.as_view(),
         name='search'),
    
    path('skills/',
         skillsEmployeeListView.as_view(),
         name='skills'),
    
    path('detail/<pk>',
         employeeDetailView.as_view(),
         name='detail'),
    
    path('register/',
         employeeCreateView.as_view(),
         name='register'),
    
    path('success/',
         successView.as_view(),
         name='success'),
    path(
     'update/<pk>',
     employeeUpdateView.as_view(),
     name='update'
    ),
    path(
     'delete/<pk>',
     employeeDeleteView.as_view(),
     name='detele'
    ),
]

proyectoEmpleados/urls.py
from django.contrib import admin
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('applications.home.urls')),
    path('',include('applications.dep.urls')),
    path('',include('applications.emp.urls')),
]

templates/includes/header.html
<div class="top-bar"   style="background:#ffffff">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu >
      <li class="menu-text">Empleados</li>
      <li>
        <a href="/">Bienvenida</a>
      </li>
      <li>
        <a href="{% url 'emp_app:allEmployees' %}">Listar Empleados</a>
      </li>
      <li>
        <a href="{% url 'dep_app:listDep' %}">Departamentos</a>
      </li>
      <li><a href="{% url 'dep_app:registerDep' %}">Registar Un Departamento</a></li>
      <div class="top-bar-right">
        <ul class="menu">
          <!--<li><input type="search" placeholder="Buscar Empleado"></li>-->
          <li><a href="{% url 'emp_app:register' %}" class="button">Registrar Nuevo Emp</a></li>
        </ul>
      </div>
    </ul>
  </div>
</div>